# Generated by Django 4.0.3 on 2022-03-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description_short', models.TextField()),
                ('description_long', models.TextField()),
                ('coordinates_lng', models.DecimalField(decimal_places=14, max_digits=16)),
                ('coordinates_lat', models.DecimalField(decimal_places=14, max_digits=16)),
            ],
        ),
    ]
