# Generated by Django 4.0.3 on 2022-03-23 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='imgs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.image'),
        ),
    ]
