# Generated by Django 4.0.3 on 2022-03-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image_place_imgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='./media/'),
        ),
    ]
