# Generated by Django 4.0.3 on 2022-03-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='feature_filename',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
