# Generated by Django 4.0.3 on 2022-03-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_remove_place_feature_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='position',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
