# Generated by Django 4.0.3 on 2022-04-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_alter_image_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Позиция'),
        ),
    ]
